spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: password
  application:
    security:
      jwt:
        expiration: 86400000
mybatis:
  configuration:
    map-underscore-to-camel-case: true  #駝峰命名與下畫線命名的自動轉換